### ISSUE TITLE
Firefox cannot access DNS when running inside jail, no GPU rendering due to missing glxtest permissions

### ISSUE THREAD

**Issue by adworacz** [igo95862/bubblejail#80]
### Output of `bubblejail --version`

0.8.2

### Your distro name and version

Archlinux - latest updates

### Description

Starting firefox using the `firefox_wayland` profile results in firefox not being able to use DNS for some reason. I can access sites when using IP addresses, like `https://1.1.1.1`, but anything with a domain name immediately fails to resolve.

Additionally, GPU acceleration appears to be disabled, even with direct rendering enabled. This appears to be because the `glxtest` executable cannot run, based on the firefox logs:

```
[GFX1-]: FireTestProcess failed: Failed to spawn child process “/usr/lib/firefox/glxtest” (Operation not permitted)
[GFX1-]: glxtest: ManageChildProcess failed
[GFX1-]: No GPUs detected via PCI
```

Instance config:
```
[common]
executable_name = "/usr/bin/firefox"
share_local_time = false
filter_disk_sync = false
dbus_name = "org.mozilla.*"

[wayland]

[network]

[home_share]
home_paths = [
    "Downloads",
]

[direct_rendering]
enable_aco = false

[notify]

[pipewire]
```

**Comment by adworacz** [comment]
Great question - I am using `systemd-resolved`, so:

`ls -l` shows:

```
lrwxrwxrwx 1 root root 37 Jul  2 10:44 /etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf
```

**Comment by igo95862** [comment]
Hello @adworacz 

> Great question - I am using `systemd-resolved`, so:
> 
> `ls -l` shows:
> 
> ```
> lrwxrwxrwx 1 root root 37 Jul  2 10:44 /etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf
> 

This is obvious. The `/run` directory is separated in the sandbox so `/run/systemd/resolve/stub-resolv.conf` does not exist.

```
[GFX1-]: FireTestProcess failed: Failed to spawn child process “/usr/lib/firefox/glxtest” (Operation not permitted)
[GFX1-]: glxtest: ManageChildProcess failed
[GFX1-]: No GPUs detected via PCI
```

I am getting a different error:

```
WARNING
cannot access /sys/bus/pci
ERROR
Unable to open a connection to the X server
```

But passing glxtest `--wayland` option makes it successfully run:

```
WARNING
cannot access /sys/bus/pci
DRI_DRIVER
iris
VENDOR
Intel

DRM_RENDERDEVICE
/dev/dri/renderD128
MESA_VENDOR_ID
0x8086
MESA_DEVICE_ID
0x9b41
TEST_TYPE
EGL
```

**Comment by igo95862** [comment]
@adworacz I pushed the [`follow-resolv-conf-symlinks`](https://github.com/igo95862/bubblejail/tree/follow-resolv-conf-symlinks) branch with a possible fix to the `resolv.conf` being a symlink. Can you give it a test?

**Comment by tslilc** [comment]
personally the above change crashes for me, but an easy work around in the case of systemd-resolved stub-resolv symlinks appears to be
```
[root_share]
paths = []
read_only_paths = [
     "/var/run/systemd/resolve/stub-resolv.conf",
]
```

**Comment by igo95862** [comment]
> personally the above change crashes for me

How exactly does it crash? Can you give an error log so I can fix it.

**Comment by tslilc** [comment]
@igo95862 i believe you may be able to reproduce this by making your /etc/resolv.conf a symlink to something outside of the usual shared paths. Nevertheless, 

```
$ bubblejail run firefox-radix 
bwrap: Can't create file at /etc/resolv.conf: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 32, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 243, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 111, in run_bjail
    async_run(
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 255, in async_run_init
    raise BubblewrapRunError((
bubblejail.exceptions.BubblewrapRunError: Bubblewrap failed. Try running bubblejail in terminal to see the exact error.
```

**Comment by igo95862** [comment]
Probably the order of bind commands is not right.

I will try to fix it tomorrow by intentionally creating a symlink on my system.

**Comment by igo95862** [comment]
I used the strace and I think I know what is going on.

```
9405  newfstatat(AT_FDCWD, "/newroot/etc/resolv.conf", 0x7fff2dac02f0, 0) = -1 ENOENT (No such file or di
rectory)
9405  creat("/newroot/etc/resolv.conf", 0444) = -1 ENOENT (No such file or directory)
```

So the issue is that because the `/newroot/etc/resolv.conf` is a symlink the syscalls fails because it redirects to the `/run/`. There is flag [`AT_SYMLINK_NOFOLLOW`](https://man.archlinux.org/man/newfstatat.2#AT_SYMLINK_NOFOLLOW) to not follow symlinks but it does not look like bubblewrap use it or there is an option to enable it.

**Comment by igo95862** [comment]
@adworacz I pushed d09981374c851e1bcfd5a6849304be1bb2a6b887 which will mount the path of the actual file.

Meanwhile I will also look in to bubblewrap and if it can make use of `AT_SYMLINK_NOFOLLOW`.

**Comment by igo95862** [comment]
Looks like bubblewrap has an opened issues about symlinks following: 

https://github.com/containers/bubblewrap/issues/390

I wonder if a new mounting API can be used to fix this issue.

**Comment by adworacz** [comment]
Ahhhh, actually, the glxtest issues aren't caused by bubblejail - they're caused by my Apparmor profile.

Example from my logs:
```
DENIED  firefox exec @{lib}/firefox/glxtest -> firefox-glxtest info="no new privs" comm=firefox requested_mask=x denied_mask=x error=-1
```


Setting the profile to `complain` mode properly enables GPU support of WebRender.

I'll work on fixing my Apparmor profile to support the Bubblejail use case.

**Comment by adworacz** [comment]
Yeah, it’s not that glxtest is being blocked directly. It works just fine with apparmor outside of bubblejail. 

But there appears to be a change in behavior when operating inside of bubblewrap. The links you provide might be the key. 

I’ll do some reading and experimentation to see if I can find a fix.

**Comment by xiota** [comment]
Is GPU acceleration really disabled?  Or is `glxtest` just being noisy?  [bugzilla:1868782](https://bugzilla.mozilla.org/show_bug.cgi?id=1868782) indicates "those strings were mostly for debugging/display purposes" and are not associated with any loss of functionality.

On X11 without apparmor, `intel_gpu_top` shows acceleration is used, but I still have the following error.
```
[GFX1-]: glxtest: cannot access /sys/bus/pci
```

When I add `/sys/bus/pci` to root share, the following are shown.
```
[GFX1-]: glxtest: ManageChildProcess failed

[GFX1-]: No GPUs detected via PCI
```

**Comment by igo95862** [comment]
I think I should enable the direct rendering on by default for Firefox. Chromium already has this.

**Comment by igo95862** [comment]
> Just a clarification that enabling that option doesn't remove the glxtest error notice. I think I worded my previous post in a way that didn't make that clear.

You should check for the exit code, not the error messages it prints.

On my system running `/usr/lib/firefox/glxtest --wayland` will run successfully (exit code 0) even if it prints the `cannot access /sys/bus/pci`.

**Comment by igo95862** [comment]
> Running `/usr/lib/firefox/glxtest --wayland` manually in my terminal doesn't produce any GPU related error string for me. Should I be running it in some special mount point or file?

Sorry I meant running the glxtest manually inside the sandbox. You can run some terminal application inside the same sandbox as Firefox. I usually use alacrity:  `bubblejail run Firefox alacritty` This can be done at the same time the Firefox is running.

**Comment by trytomakeyouprivate** [comment]
Could we split up the DNS issues from the GPU issues? This is a bit confusing ;D

**Comment by igo95862** [comment]
The DNS issue should be fixed with a6a2719410b95618a9c2dac1337a7f1a9a8d922f.

As for the glxtest issue I can't replicate it. My Firefox works fine and the hardware video acceleration is also working.
